var tgTitle = "Science Book";
var treeStructure = ["class", "chapter", "type"];
var imagePath = "img/q_img/";

var questions = [
  // MCQ Qustions
  // {
  //   excel_id: "english6",
  //   class: "Class - 1",
  //   subject: "",
  //   book: " Class - 1",
  //   chapter: "1. Parts of a Plant",
  //   type: "Multiple choice questions",
  //   answer: ["ii"],
  //   difficulty: "M",
  //   outcome: "Understand",
  //   mark: 1,
  //   question: {
  //     title: "A. Tick (&#10003;) the correct sentences.",
  //     option: [
  //       "Gappu and Gunnu woke up after the storm and went for a walk.",
  //       "i. Decimal Number System",
  //       "ii. Binary Number System",
  //       "iii. Octal Number System",
  //       "iv. None of these",
  //     ],
  //     image: "",
  //   },
  // },

  // True or False Questions
  {
    excel_id: "english6",
    class: "Class - 7",
    subject: "",
    book: "Class - 7",
    chapter: "1. Living and Non-living Things",
    type: "Write True or False",
    answer: ["F"],
    difficulty: "E",
    outcome: "Understand",
    mark: 1,
    question: {
      title: "Write T if the statement is True and F if it is False.",
      option: [
        "Human beings, plants and animals are living things. <br> (i) T <br> (ii) F ",
      ],
      image: "",
    },
  },
  {
    excel_id: "english6",
    class: "Class - 7",
    subject: "",
    book: "Class - 7",
    chapter: "1. Living and Non-living Things",
    type: "Write True or False",
    answer: ["F"],
    difficulty: "E",
    outcome: "Understand",
    mark: 1,
    question: {
      title: "Write T if the statement is True and F if it is False.",
      option: ["Living things do not have babies. <br> (i) T <br> (ii) F "],
      image: "",
    },
  },
  {
    excel_id: "english6",
    class: "Class - 7",
    subject: "",
    book: "Class - 7",
    chapter: "1. Living and Non-living Things",
    type: "Write True or False",
    answer: ["F"],
    difficulty: "E",
    outcome: "Understand",
    mark: 1,
    question: {
      title: "Write T if the statement is True and F if it is False.",
      option: [
        "Non-living things need to breathe in air to stay alive. <br> (i) T <br> (ii) F ",
      ],
      image: "",
    },
  },
  {
    excel_id: "english6",
    class: "Class - 7",
    subject: "",
    book: "Class - 7",
    chapter: "1. Living and Non-living Things",
    type: "Write True or False",
    answer: ["F"],
    difficulty: "E",
    outcome: "Understand",
    mark: 1,
    question: {
      title: "Write T if the statement is True and F if it is False.",
      option: ["Non-living things do not need food. <br> (i) T <br> (ii) F  "],
      image: "",
    },
  },
  {
    excel_id: "english6",
    class: "Class - 7",
    subject: "",
    book: "Class - 7",
    chapter: "1. Living and Non-living Things",
    type: "Write True or False",
    answer: ["F"],
    difficulty: "E",
    outcome: "Understand",
    mark: 1,
    question: {
      title: "Write T if the statement is True and F if it is False.",
      option: [
        "All living things move in some way or the other. <br> (i) T <br> (ii) F ",
      ],
      image: "",
    },
  },

  // Fill in the blanks

  {
    excel_id: "english6",
    class: "Class - 7",
    subject: "",
    book: "Class - 7",
    chapter: "2. Parts of a Plant",
    type: "Fill in the blanks",
    answer: [""],
    difficulty: "M",
    outcome: "Understand",
    mark: 1,
    question: {
      title: "Fill in the blanks by unscrambling the words given in brackets. ",
      option: [
        "The ___________ is an important part of the shoot system. (METS)",
      ],
      image: "",
    },
  },
  {
    excel_id: "english6",
    class: "Class - 7",
    subject: "",
    book: "Class - 7",
    chapter: "2. Parts of a Plant",
    type: "Fill in the blanks",
    answer: [""],
    difficulty: "M",
    outcome: "Understand",
    mark: 1,
    question: {
      title: "Fill in the blanks by unscrambling the words given in brackets. ",
      option: [
        "Trees have strong, thick and hard stems called __________. (KUTRNS)",
      ],
      image: "",
    },
  },
  {
    excel_id: "english6",
    class: "Class - 7",
    subject: "",
    book: "Class - 7",
    chapter: "2. Parts of a Plant",
    type: "Fill in the blanks",
    answer: [""],
    difficulty: "M",
    outcome: "Understand",
    mark: 1,
    question: {
      title: "Fill in the blanks by unscrambling the words given in brackets. ",
      option: ["Leaves give out a gas called __________. (YNXGOE)"],
      image: "",
    },
  },
  {
    excel_id: "english6",
    class: "Class - 7",
    subject: "",
    book: "Class - 7",
    chapter: "2. Parts of a Plant",
    type: "Fill in the blanks",
    answer: [""],
    difficulty: "M",
    outcome: "Understand",
    mark: 1,
    question: {
      title: "Fill in the blanks by unscrambling the words given in brackets. ",
      option: [
        "The ___________  absorbs the sunlight needed to make food for the plant. (LCOHOPLYRLH)",
      ],
      image: "",
    },
  },
  {
    excel_id: "english6",
    class: "Class - 7",
    subject: "",
    book: "Class - 7",
    chapter: "2. Parts of a Plant",
    type: "Fill in the blanks",
    answer: [""],
    difficulty: "M",
    outcome: "Understand",
    mark: 1,
    question: {
      title: "Fill in the blanks by unscrambling the words given in brackets. ",
      option: [
        "The process of growth of a plant from a seed is called __________. (RNEMIOGAINT)",
      ],
      image: "",
    },
  },

  // Short answer type questions
  {
    excel_id: "english1",
    class: "Class - 7",
    subject: "",
    book: " Class - 7",
    chapter: "2. Parts of a Plant",
    type: "Short answer type questions",
    answer: [""],
    difficulty: "M",
    outcome: "Apply",
    mark: 1,
    question: {
      title: "Define the following terms.",
      option: [
        "root system   <br/><br/>____________________________________________________</br>",
      ],
      image: "",
    },
  },
  {
    excel_id: "english1",
    class: "Class - 7",
    subject: "",
    book: " Class - 7",
    chapter: "2. Parts of a Plant",
    type: "Short answer type questions",
    answer: [""],
    difficulty: "M",
    outcome: "Apply",
    mark: 1,
    question: {
      title: "Define the following terms.",
      option: [
        " shoot system     <br/><br/>____________________________________________________</br>",
      ],
      image: "",
    },
  },
  {
    excel_id: "english1",
    class: "Class - 7",
    subject: "",
    book: " Class - 7",
    chapter: "2. Parts of a Plant",
    type: "Short answer type questions",
    answer: [""],
    difficulty: "M",
    outcome: "Apply",
    mark: 1,
    question: {
      title: "Define the following terms.",
      option: [
        " leaf blade     <br/><br/>____________________________________________________</br>",
      ],
      image: "",
    },
  },
  {
    excel_id: "english1",
    class: "Class - 7",
    subject: "",
    book: " Class - 7",
    chapter: "2. Parts of a Plant",
    type: "Short answer type questions",
    answer: [""],
    difficulty: "M",
    outcome: "Apply",
    mark: 1,
    question: {
      title: "Define the following terms.",
      option: [
        "germination  <br/><br/>____________________________________________________</br>",
      ],
      image: "",
    },
  },
  // Long answer type questions
  {
    excel_id: "english1",
    class: "Class - 7",
    subject: "",
    book: " Class - 7",
    chapter: "1. Living and Non-living Things",
    type: "Long answer type questions",
    answer: [""],
    difficulty: "M",
    outcome: "Apply",
    mark: 1,
    question: {
      title: "Answer these questions.",
      option: [
        "Define living things. Describe any two features of living things. <br/><br/>____________________________________________________</br>",
      ],
      image: "",
    },
  },
  {
    excel_id: "english1",
    class: "Class - 7",
    subject: "",
    book: " Class - 7",
    chapter: "1. Living and Non-living Things",
    type: "Long answer type questions",
    answer: [""],
    difficulty: "M",
    outcome: "Apply",
    mark: 1,
    question: {
      title: "Answer these questions.",
      option: [
        "Define non-living things. Describe any two features of non-living things. <br/><br/>____________________________________________________</br>",
      ],
      image: "",
    },
  },
  {
    excel_id: "english1",
    class: "Class - 7",
    subject: "",
    book: " Class - 7",
    chapter: "1. Living and Non-living Things",
    type: "Long answer type questions",
    answer: [""],
    difficulty: "M",
    outcome: "Apply",
    mark: 1,
    question: {
      title: "Answer these questions.",
      option: [
        "How do living things breathe? Name and explain the organs they use. <br/><br/>____________________________________________________</br>",
      ],
      image: "",
    },
  },
  {
    excel_id: "english1",
    class: "Class - 7",
    subject: "",
    book: " Class - 7",
    chapter: "1. Living and Non-living Things",
    type: "Long answer type questions",
    answer: [""],
    difficulty: "M",
    outcome: "Apply",
    mark: 1,
    question: {
      title: "Answer these questions.",
      option: [
        " All living things move in some way or the other. Explain. <br/><br/>____________________________________________________</br>",
      ],
      image: "",
    },
  },
  {
    excel_id: "english1",
    class: "Class - 7",
    subject: "",
    book: " Class - 7",
    chapter: "2. Parts of a Plant",
    type: "Long answer type questions",
    answer: [""],
    difficulty: "M",
    outcome: "Apply",
    mark: 1,
    question: {
      title: "Answer these questions.",
      option: [
        "Name the two main types of roots. Explain with examples. <br/><br/>____________________________________________________</br>",
      ],
      image: "",
    },
  },
  {
    excel_id: "english1",
    class: "Class - 7",
    subject: "",
    book: " Class - 7",
    chapter: "2. Parts of a Plant",
    type: "Long answer type questions",
    answer: [""],
    difficulty: "M",
    outcome: "Apply",
    mark: 1,
    question: {
      title: "Answer these questions.",
      option: [
        "State the functions of the stem. Name some plants whose stems store extra food. <br/><br/>____________________________________________________</br>",
      ],
      image: "",
    },
  },
  {
    excel_id: "english1",
    class: "Class - 7",
    subject: "",
    book: " Class - 7",
    chapter: "2. Parts of a Plant",
    type: "Long answer type questions",
    answer: [""],
    difficulty: "M",
    outcome: "Apply",
    mark: 1,
    question: {
      title: "Answer these questions.",
      option: [
        " What is a leaf? Describe its features and explain how it makes food for the plant. <br/><br/>____________________________________________________</br>",
      ],
      image: "",
    },
  },
  {
    excel_id: "english1",
    class: "Class - 7",
    subject: "",
    book: " Class - 7",
    chapter: "2. Parts of a Plant",
    type: "Long answer type questions",
    answer: [""],
    difficulty: "M",
    outcome: "Apply",
    mark: 1,
    question: {
      title: "Answer these questions.",
      option: [
        "How do flowers help the plant? Explain. <br/><br/>____________________________________________________</br>",
      ],
      image: "",
    },
  },
  {
    excel_id: "english1",
    class: "Class - 7",
    subject: "",
    book: " Class - 7",
    chapter: "2. Parts of a Plant",
    type: "Long answer type questions",
    answer: [""],
    difficulty: "M",
    outcome: "Apply",
    mark: 1,
    question: {
      title: "Answer these questions.",
      option: [
        " What are seeds? Give examples. Explain the process of germination.  <br/><br/>____________________________________________________</br>",
      ],
      image: "",
    },
  },
];
